### ISSUE TITLE
Datetimepicker arrow bug

### ISSUE THREAD

**Issue by ksxio** [visionappscz/synergic-ui#72]
Datetimepicker showing arrows at actual date (doesn't rely on selected date.

Tested in Safari and Chrome on OS X and Firefox and Chrome on Win 10, so it's browser independent. 

<img width="859" alt="screen shot 2016-06-15 at 10 34 33" src="https://cloud.githubusercontent.com/assets/535900/16073830/1a8f1f7a-32e8-11e6-980c-6024e7166656.png">

<img width="313" alt="screen shot 2016-06-15 at 10 34 41" src="https://cloud.githubusercontent.com/assets/535900/16073826/1411ced6-32e8-11e6-8d75-ec3b728c94a1.png">

**Comment by crishpeen** [comment]
Pseudo element td.today:before has wrong *border-width*. 
Should be:
```
.bootstrap-datetimepicker-widget table td.today:before {
 content: ''; display: inline-block;
 border: solid transparent;
 border-width: 0 0 7px 7px;
 border-bottom-color: #337ab7;
 border-top-color: rgba(0, 0, 0, 0.2);
 position: absolute;
 bottom: 4px;
 right: 4px;
}
```
But currently is compiled as:
```
.bootstrap-datetimepicker-widget table td.today:before {
 content: '';
 display: inline-block;
 border: 7px solid transparent;
 border-bottom-color: #00778b;
 border-top-color: rgba(0,0,0,.2);
 position: absolute;
 bottom: 4px;
 right: 4px;
}
```
